config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
end

Spree::Core::Engine.add_routes do
  namespace :admin, path: Spree.admin_path do
    resources :cms_blocks
    resources :pages do
      collection do
        get '/category/:category' => 'pages#index'
        get '/category/:category/new' => 'pages#new'
        get '/category/:category/:id/edit' => 'pages#edit'
      end
    end

    post 'upload' => 'upload#upload'
  end
  constraints(Spree::StaticPage) do
    get '/(*path)', to: 'static_content#show', as: 'static'
  end
end

app/models/spree/page.rb
class Spree::Page < Spree::Base
  sir_trevor_content :body

  default_scope { order(position: :asc) }

  has_and_belongs_to_many :stores, join_table: 'spree_pages_stores'
  has_many :images, -> { order(:position) },
           as: :viewable, dependent: :destroy, class_name: 'Spree::CmsImage'

  validates :title, presence: true
  validates :slug, presence: true
  validates :layout, presence: true
  validates :slug, uniqueness: true

  scope :visible, -> { where(visible: true) }
  scope :header_links, -> { where(show_in_header: true).visible }
  scope :footer_links, -> { where(show_in_footer: true).visible }
  scope :sidebar_links, -> { where(show_in_sidebar: true).visible }

  # Base category scope
  scope :page, -> { where(category: ['page', '', nil]) }

  scope :by_store, ->(store) { joins(:stores).where('spree_pages_stores.store_id = ?', store) }

  before_save :update_positions_and_slug

  def initialize(*args)
    super(*args)
    last_page = Spree::Page.last
    self.position = last_page ? last_page.position + 1 : 0
  end

  def link
    slug
  end

  def blocks(type = nil)
    return body.to_a if type.nil?

    body.to_a.select { |block| block_type? block, type }
  end

  private

  def block_type(block)
    block.class.name.split('::').last
  end

  def block_type?(block, type)
    block_type(block) == type
  end

  def update_positions_and_slug
    # Ensure that all slugs start with a slash.
    slug.prepend('/') unless slug.start_with?('/')
    return if new_record?
    return unless (prev_position = Spree::Page.find(id).position)
    if prev_position > position
      Spree::Page.where('? <= position and position < ?', position, prev_position).update_all('position = position + 1')
    elsif prev_position < position
      Spree::Page.where('? < position and position <= ?', prev_position, position).update_all('position = position - 1')
    end
  end
end

app/views/spree/admin/pages/_form.html.erb
<% page_category = @page.persisted? ? @page.category : (@category || 'page') %>
<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:back_to_resource_list, resource: plural_resource_name(Spree::Page)), spree.admin_pages_path, icon: 'arrow-left', class: 'btn-primary' %>
<% end %>

<%= form_for [:admin, resource],
             data: {
               pageid: @page.id,
               asset_host:  Rails.configuration.asset_host
             } do |f| %>
  <%= f.hidden_field :category, value: page_category %>
  <div class="row" data-hook="admin_page_form_fields">
    <div class="col-md-6" data-hook="admin_page_form_left">
      <div class="form-group">
        <%= f.label :title %> <span class="required">*</span>
        <%= f.text_field :title, class: 'form-control' %>
        <%= f.error_message_on :title %>
      </div>

      <div class="form-group">
        <%= f.label :slug %> <span class="required">*</span>
        <%= f.text_field :slug, class: 'form-control' %>
        <%= f.error_message_on :slug %>
      </div>

      <div class="form-group">
        <%= f.label :meta_title %>
        <%= f.text_field :meta_title, class: 'form-control' %>
        <%= f.error_message_on :meta_title %>
      </div>

      <div class="form-group">
        <%= f.label :meta_keywords %>
        <%= f.text_field :meta_keywords, class: 'form-control' %>
        <%= f.error_message_on :meta_keywords %>
      </div>

      <div class="form-group">
        <%= f.label :meta_description %>
        <%= f.text_field :meta_description, class: 'form-control' %>
        <%= f.error_message_on :meta_description %>
      </div>
    </div>

    <% layouts = SpreeCms.configuration.layouts[page_category] %>
    <% options = options_for_select(layouts.map { |title, key| [key, title] },
                                    selected: @page.layout || (layouts.first if layouts.size == 1) ) %>
    <div class="col-md-6" data-hook="admin_page_form_right">
      <div class="form-group">
        <%= f.label :layout %> <span class="required">*</span>
        <%= select_tag 'page[layout]', options,
             { id: 'page_layout', include_blank: 'Select layout', class: 'select2' } %>
        <%= f.error_message_on :layout %>
      </div>

      <div class="form-group">
        <%= f.label :position %>
        <%= f.number_field :position, min: 0, class: 'form-control' %>
      </div>

      <div class="checkbox">
        <%= f.label :visible do %>
          <%= f.check_box :visible %>
          <%= Spree::Page.human_attribute_name(:visible) %>
        <% end %>
      </div>

      <div class="form-group">
        <%= f.label :stores, plural_resource_name(Spree::Store) %>
        <% Spree::Store.all.each do |store| %>
          <div class="checkbox">
            <%= f.label store.name.downcase.to_sym do %>
              <%= check_box_tag 'page[store_ids][]', store.id, @page.stores.include?(store) %>
              <%= store.name %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <% if f.object.persisted? %>
    <div class="row" data-hook="admin_page_form_meta">
      <div class="col-xs-12">
        <div class="form-group">
          <%= f.label :content %>
          <%= f.text_area :body, rows: 12, class: 'form-control js-st-instance', data: { category: page_category } %>
          <%= f.error_message_on :body %>
        </div>
      </div>
    </div>
  <% end %>

  <div class="row" data-hook="admin_page_form_additional_fields">
    <div class="col-md-12"></div>
  </div>

  <%= render "spree/admin/shared/#{resource.new_record? ? 'new' : 'edit'}_resource_links" %>
<% end %>

app/views/spree/admin/pages/edit.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:editing_resource, resource: @page.category.titleize) %>
<% end %>

<%= render 'form', resource: @page %>

app/views/spree/admin/pages/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(@category.pluralize) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_page, scope: :static_content), "/admin/pages/category/#{@category}/new", icon: 'plus', class: 'btn-primary', id: 'admin_new_page' %>
<% end %>

<% if @pages.any? %>
  <table class="table" id="listing_pages" data-hook>
    <colgroup>
      <col style="width: 20%">
      <col style="width: 35%">
      <col style="width: 15%">
      <col style="width: 15%">
      <col style="width: 15%">
    </colgroup>
    <thead>
      <tr data-hook="admin_pages_index_headers">
        <th><%= Spree::Page.human_attribute_name(:title) %></th>
        <th><%= Spree.t(:link, scope: :static_content) %></th>
        <th><%= Spree::Page.human_attribute_name(:layout) %></th>
        <th class="text-center"><%= Spree::Page.human_attribute_name(:visible) %></th>
        <th data-hook="admin_pages_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @pages.each do |page| %>
        <tr data-hook="admin_pages_index_rows" class="<%= cycle('odd', 'even') %>" id="<%= dom_id page %>">
          <td><%= page.title %></td>
          <td><%= link_to page.link, page.link, target: '_blank' %></td>
          <td><%= page.layout %></td>
          <td class="text-center"><%= content_tag(:i, '', class: 'icon icon-ok') if page.visible %></td>
          <td class="actions text-right" data-hook="admin_pages_index_row_actions">
            <%= link_to_edit page, no_text: true %>
            <%= link_to_delete page, no_text: true %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-warning no-objects-found">
    <%= Spree.t(:no_resource_found, resource: Spree::Page.model_name.human) %>,
    <%= link_to Spree.t(:add_one), "/admin/pages/category/#{@category}/new" %>!
  </div>
<% end %>

app/views/spree/admin/pages/new.html.erb
<% content_for :page_title do %>
  <%= Spree.t("new_#{@category}", scope: :static_content) %>
<% end %>

<%= render 'form', resource: @page %>